#pragma config(Motor,  port2,           LeftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Claw1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftArm,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Claw2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int joyThresh = 10; // This variable controls the size of the deadzone for the joysticks
bool cubeResist = false; // This sets a special case for when the robot needs to pick up a cube

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(115)

#include "Vex_Competition_Includes.c"


/**
*
* DriveControl moves the drive based upon the inputs from the parameters
* @param leftPower int -128 to 127
* @param rightPower int -128 to 127
*
*/

int mapJoyInt (TVexJoysticks input)
{
    if (abs(vexRT[input]) > joyThresh)
    {
        return vexRT[input];
    }
    return 0;
}

void driveControl (int leftPower, int rightPower)
{
	motor[LeftBack] = leftPower;
	motor[LeftFront] = leftPower;
	motor[RightBack] = rightPower;
	motor[RightFront] = rightPower;
}

int mapButtonInt5()
{
		if(vexRT[Btn5D])
		{
        return -128;
    }
    else if(vexRT[Btn5U])
    {
        return 127;
    }
    else
    {
    return -50;
  }
}

int mapButtonInt6(){
		if(vexRT[Btn6D]){
        return -128;
    }
    else if(vexRT[Btn6U]){
        return 127;
    }
    else
    {
    return 0;
  	}
}

void armControl (int power){
	motor[RightArm] = power;
	motor[LeftArm] = power;
}

void clawControl (int power){
	motor[Claw1] = power;
	motor[Claw2] = power;
}

void resetMotors(){
    motor[LeftBack] = 0;
    motor[LeftFront] = 0;
    motor[RightBack] = 0;
    motor[RightFront] = 0;
    motor[RightArm] = 0;
    motor[LeftArm] = 0;
    motor[Claw1] = 0;
    motor[Claw2] = 0;
}

/**
*
* mapJoyInt takes the TVexJoysticks input value and a threshold value and returns an integer
* @param TVexJoysticks is a created variable that accepts joystick channels
* @param threshold is an int -128 to 127
*
*/

//Divider for readability

void pre_auton()
{

}

//Divider for readability

task autonomous()
{

}

//Divider for readability

task usercontrol()
{
    while (true)
	{
		driveControl(mapJoyInt(Ch3),mapJoyInt(Ch2));
		armControl(mapButtonInt6());
		clawControl(mapButtonInt5());
	}
}
